version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web-app:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgresdb
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: postgres

volumes:
  postgres-data:
